name: Deploy Finance Chat Bot

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Verify Google libraries are installed in venv
          python -c "import google.auth; import googleapiclient.discovery; print('Google libraries installed in venv')"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Setup Google Sheets
        continue-on-error: true
        if: false # Skip this step to avoid deployment failures
        env:
          GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          echo "Skipping Google Sheets setup during deployment"
          echo "Sheets will be set up on first bot usage"

      - name: Deploy with Zappa (with retry)
        run: |
          source venv/bin/activate
          zappa deploy ${{ matrix.environment }} || zappa update ${{ matrix.environment }}

      - name: Deployment Summary
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "🔗 Lambda URL: ${{ steps.get-url.outputs.LAMBDA_URL }}"
          echo ""
          echo "✅ Your bot is now live! Next steps:"
          echo "1. Find your bot on Telegram and start a chat"
          echo "2. Send /start to see the welcome message"
          echo "3. Test with: 'Coffee $5.50' or send a receipt photo"
          echo "4. Use /summary to check monthly totals"
          echo "5. Use /setup if Google Sheets setup failed"
          echo ""
          echo "📊 Check your Google Sheets for logged expenses!"
